### ISSUE TITLE
the README file lack modal cover

### ISSUE THREAD

**Issue by blueveinsyin** [BossBele/cropzee#1]
<div id="cropzee-modal-cover" class="cropzee-modal-cover">
    </div>
    this cover should be added in the README file, otherwise the plugin does not work.
    By the way, thanks for your contribution.

**Comment by BossBele** [comment]
@blueveinsyin thanks for the notification. README file now updated. Watch for version 2 of cropzee. Contact me adambeleko@gmail.com and let's work together.
