### ISSUE TITLE
Model example not works

### ISSUE THREAD

**Issue by tomasr1981** [BossBele/cropzee#16]
Hi, I change rotation in this way, but there have to be some bug with cropzeeCroppr.getValue().
Here is model https://raw.githack.com/heldersepu/hs-scripts/master/HTML/crop.html#
Is that bug or what is problem with that?

**Comment by BossBele** [comment]
Hello, sorry for the late reply..
I see it working well in the link you sent. I can't really see the value you're getting since the upload functionality is inactive.
However, if you want to get the value, you shoud do it when the user crops the image - in your case, when the user clicks "done".
